### ISSUE TITLE
remove object

### ISSUE THREAD

**Issue by Arcxml** [TencentARC/BrushNet#10]
Hi, thanks for your code. I have a question, if I want to remove an object (for example I want to remove this blueberry), how should I write the prompt? If I wrote "remove the blueberry" it might not work well.
![image](https://github.com/TencentARC/BrushNet/assets/138861545/2db0efba-7dde-41f3-afbf-4819df10bfde)

**Comment by juxuan27** [comment]
Hi, @Arcxml ! Thank you for your focus. The hugging face space uses the segmentation mask checkpoint, thus it will force a boundary in the mask region. I recommend you use a random segmentation mask checkpoint and add blueberry to the negative prompt. Since it is really hard for the diffusion model to understand remove xxx.

**Comment by Arcxml** [comment]
hello, thank for your reply. Do you think this is the problem from prompt? Or maybe another prompt will work for my task?



---- Replied Message ----
| From | Xuan ***@***.***> |
| Date | 03/31/2024 13:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TencentARC/BrushNet] remove object (Issue #10) |

Hi, @Arcxml ! Thank you for your focus. The hugging face space uses the segmentation mask checkpoint, thus it will force a boundary in the mask region. I recommend you use a random segmentation mask checkpoint and add blueberry to the negative prompt. Since it is really hard for the diffusion model to understand remove xxx.

**Comment by juxuan27** [comment]
I think the prompt will influence the results. But as I said, I believe the most important reason is the ckpt used in hugging face space. You can try locally changing the ckpt to the random mask one, which can be downloaded from the Google Drive link we provide. I think this may lead to a better result~ 

Using the segmentation mask ckpt can successfully remove the blueberry by putting blueberry in the negative prompt. However, it would lead to incoherent results due to the force of generating a boundary.

**Comment by juxuan27** [comment]
As mentioned in my previous comments, you need to use random mask ckpt instead of segmentation mask ckpt to remove objects.

**Comment by Arcxml** [comment]
Okay, thanks a lot！



---- Replied Message ----
| From | Xuan ***@***.***> |
| Date | 04/02/2024 19:03 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [TencentARC/BrushNet] remove object (Issue #10) |

As mentioned in my previous comments, you need to use random mask ckpt instead of segmentation mask ckpt to remove objects.
