### ISSUE TITLE
strength option

### ISSUE THREAD

**Issue by loboere** [TencentARC/BrushNet#6]
There is an option like strength, what I want is for the masked part to take the color of the original image.

**Comment by juxuan27** [comment]
Hi, @loboere ! Thank you for your focus. The strength used in our paper is to control the unmasked region, thus seems not suitable for your requirements. I think you can try several approaches: (1) using the operation proposed in sdedit, which means you denoise from a noised original image instead of pure noise. (2) using plugs such as ip-adapter, which can control the style and color of the generated image.
